#!/usr/bin/bash
#
# Put customizations to your image in this file.

MUNIN_PLUGIN_VERSION='0.2'

PATH=/opt/local/gnu/bin:/opt/local/bin:/opt/local/sbin:/usr/bin:/usr/sbin

# Exit if any commands fail
set -o errexit

# Ensure we have updated standard packages
echo "* Updating standard packages.";
pkg_delete -v nodejs smtools
pkg_add -v nodejs smtools dtracetools htop
npm install smartdc -g
npm install jsontool -g

# Configuring image specific packages
echo "* Configuring image specific packages.";
pkg_add http://pkgsrc.smartos.skylime.net/skylime-extra/2014Q1/x86_64/spiped-1.3.1nb3.tgz

echo "* Installing API Server."
L3REL=0.0.4
mkdir /var/www
cd /var/www
wget https://github.com/wiedi/limeade3/archive/v${L3REL}.tar.gz
tar zxf v${L3REL}.tar.gz
mv limeade3-${L3REL}/ limeade3
rm v${L3REL}.tar.gz
cd -

echo "* Install Python dependencies."
pip3 install -r /var/www/limeade3/req.txt
pip3 install -U git+https://github.com/lsbardel/python-stdnet.git@af8ca652d92ad4c00dbbbdec377ad69985a27992

echo "* Generating Static files."
cd /var/www/limeade3
python3.3 manage.py collectstatic --noinput
cd -

echo "* Create ssl folder"
mkdir -p /opt/local/etc/nginx/ssl

echo "* Create database."
cd /var/www/limeade3
python3.3 manage.py syncdb --noinput
cd -

echo "* Setup uwsgi and nginx."
mkdir -p /opt/local/etc/uwsgi
svccfg import /tmp/uwsgi.xml
svccfg import /tmp/mdata-setup.xml
rm /tmp/uwsgi.xml /tmp/mdata-setup.xml

# Create munin template file that will be used during mdata setup
echo "* Create munin template file that will be used during mdata setup"
cp /opt/local/etc/munin/munin-node.conf /opt/local/etc/munin/munin-node.conf.tpl

# Download and install community munin plugins
echo "* Download and install community munin plugins (overwrite all other plugins)"
curl -L https://github.com/drscream/smartos-munin-plugins/archive/v${MUNIN_PLUGIN_VERSION}.tar.gz | tar xz -C /opt/local/lib/munin/plugins

# Create rsyslog.d folder for extra configuration files
echo "* Create rsyslog.d folder for extra configuration files"
mkdir -p /opt/local/etc/rsyslog.d
echo '
# Include additional config files from extra folder
$IncludeConfig /opt/local/etc/rsyslog.d/*.conf' >> /opt/local/etc/rsyslog.conf

# Clean up
echo "* Cleaning up."
rm -rf /root/*

# Prepare image for provisioning
sm-prepare-image -y
