#!/usr/bin/bash
#
# Put customizations to your image in this file.

PATH=/opt/local/gnu/bin:/opt/local/bin:/opt/local/sbin:/usr/bin:/usr/sbin

# Munin plugins
MUNIN_PLUGINS="
	nginx_request
	nginx_status
	redis_connected_clients
	redis_per_sec
	redis_used_keys
	redis_used_memory
"

# Exit if any commands fail
set -o errexit

echo "* Installing API Server."
L3REL=0.0.9
mkdir -p /var/www/limeade3
curl -L https://github.com/wiedi/limeade3/archive/v${L3REL}.tar.gz | gtar xz -C /var/www/limeade3 --strip-components=1

echo "* Install Python dependencies."
pip3.4 install -r /var/www/limeade3/req.txt
pip3.4 install -U git+https://github.com/lsbardel/python-stdnet.git@af8ca652d92ad4c00dbbbdec377ad69985a27992

echo "* Generating Static files."
cd /var/www/limeade3
python3.4 manage.py collectstatic --noinput
cd -

echo "* Create ssl folder"
mkdir -p /opt/local/etc/nginx/ssl

echo "* Create database."
cd /var/www/limeade3
python3.4 manage.py syncdb --noinput
cd -

echo "* Setup gunicorn and nginx."
mkdir -p /opt/local/etc/gunicorn
svccfg import /tmp/gunicorn.xml
rm /tmp/gunicorn.xml

# Activate munin plugins
echo "* Activate munin plugins"
/opt/core/bin/munin-node-plugins ${MUNIN_PLUGINS}

# Clean up
echo "* Cleaning up."
rm -rf /root/*

# Prepare image for provisioning
sm-prepare-image -y
